
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MiniJiraServiceImplService", targetNamespace = "http://www.polytech.unice.fr/si/4a/appserv/demos", wsdlLocation = "http://localhost:8080/minijira-back/webservices/MiniJiraService?wsdl")
public class MiniJiraServiceImplService
    extends Service
{

    private final static URL MINIJIRASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MINIJIRASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MINIJIRASERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "MiniJiraServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/minijira-back/webservices/MiniJiraService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MINIJIRASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MINIJIRASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MiniJiraServiceImplService() {
        super(__getWsdlLocation(), MINIJIRASERVICEIMPLSERVICE_QNAME);
    }

    public MiniJiraServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MINIJIRASERVICEIMPLSERVICE_QNAME, features);
    }

    public MiniJiraServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MINIJIRASERVICEIMPLSERVICE_QNAME);
    }

    public MiniJiraServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MINIJIRASERVICEIMPLSERVICE_QNAME, features);
    }

    public MiniJiraServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MiniJiraServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MiniJiraService
     */
    @WebEndpoint(name = "MiniJiraServiceImplPort")
    public MiniJiraService getMiniJiraServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "MiniJiraServiceImplPort"), MiniJiraService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MiniJiraService
     */
    @WebEndpoint(name = "MiniJiraServiceImplPort")
    public MiniJiraService getMiniJiraServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "MiniJiraServiceImplPort"), MiniJiraService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MINIJIRASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MINIJIRASERVICEIMPLSERVICE_EXCEPTION;
        }
        return MINIJIRASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
